### ISSUE TITLE
HTTPS CDN

### ISSUE THREAD

**Issue by thenets** [liferay/alloy-ui#102]
A can't use with HTTPS servers.
This isn't a problem with code, but a important thing to create a simple application without any local imports, just a HTML file.
A simple solution, in my opinion, is CloudFlare. Another option is install a free certificate from https://letsencrypt.org/

That's it :) and thanks for this awesome framework.

**Comment by jonmak08** [comment]
Hi @thenets,

We do have a secure CDN available at https://cdn.lfrs.sl/alloyui.com/3.0.1/aui/aui-min.js, but please note that this is not an official release to our CDN server.

Please let me know if you have any questions. Thanks!
