### ISSUE TITLE
Function to trigger action after rendering Alloy UI Form Builder

### ISSUE THREAD

**Issue by vionemc** [liferay/alloy-ui#104]
I wanted to append an uneditable submit button as the last child, after the form builder so it's always positioned at the bottom.

When I run this:
`$('#myForm').append('<input class="btn btn-info" onclick="save()" type="submit" value="Submit">');`

It's positioned on the top since the form builder render ran a little bit late after append.

**Comment by mairatma** [comment]
Can you show the code where you're creating the from builder instance? If you add this right after that code it should work.

**Comment by vionemc** [comment]
Yup! Already solved. It was just about code placement. I forgot to close this issue. 

Thanks!
