### ISSUE TITLE
Do not understand release page

### ISSUE THREAD

**Issue by sunishkumar** [liferay/alloy-ui#105]
I am unable to understand the release page. 

3.0.3-deprecated.42  is released after 3.1.0-deprecated.2   and 1.5.2.34 is not deprecated.

Which one should I use for a project which I indent to start next week?

**Comment by mairatma** [comment]
We support multiple older versions of alloy-ui, due to projects that are still using them. When starting a new project I'd recommend using the latest regular version, `3.1.0`, which is the latest in [npm](https://www.npmjs.com/package/alloy-ui). Let me know if that helped.

**Comment by jonmak08** [comment]
Hi @sunishkumar,

I am closing this issue if there is no further discussion regarding the various releases.  If you continue to have questions or issues regarding the various releases, please feel free to reopen this issue or file a new issue.

Please let me know if you have any questions. Thanks!
