### ISSUE TITLE
maxPageLinks doesn't exist in Alloy 2.5

### ISSUE THREAD

**Issue by Palbear** [liferay/alloy-ui#106]
Hello,

I am upgrading from Liferay 6.1 to 6.2 and have to adapt my Alloy code from 1.5 to 2.5.
My problem is that according to the example for 2.5 and 3.0 the attribute maxPageLinks still works, but actually it is not in the source code and it doesn't works. Is there any work around for this problem?
Please read this if I was't clear about this issue, it explains exactly my problem: http://ask.programmershare.com/214_17188373/ 

Best,
Palbear

**Comment by jonmak08** [comment]
Hi @Palbear,

The attribute `maxPageLinks` is only an attribute in Alloy UI 1.5.x.  In Alloy UI 2.0.x and above, this attribute was removed and replaced with the attribute `total`.  I have created a JIRA ticket in our system for this issue at https://issues.liferay.com/browse/AUI-3098.

Please let me know if you have any questions. Thanks for reporting this issue and making our product and website better!
