### ISSUE TITLE
Custom popover in scheduler

### ISSUE THREAD

**Issue by harish278** [liferay/alloy-ui#107]
Is it possible to display custom popover on click of event, instead of edit event form.

Use case I have is that I have to show more-details of the event instead of the edit option.

If it is possible can you please point me to an example.

Thanks in advance.

**Comment by brandizzi** [comment]
Hello @harish278!

Do you want to change the popover in Liferay's calendar application, or are you using the scheduler in your own application?

Also, could you show us a screenshot of the popover as it is today, and annotate it to show us what you want to change?

Thanks!

**Comment by brandizzi** [comment]
What a pity, I really wanted to know what we could do here :( ;)

**Comment by HatsuSakura** [comment]
Hello, I'd like to reopen this thread.
I'm trying to create a custom input popover for the SchedulerEventRecorder: I need to insert and save more options than just the title.
For the project purpose I need to chose one among a set of event categories and one among a set of event owner while creating the event.
Can you give me some tips, please!
Thank you in advance
