### ISSUE TITLE
how to add zoom in and zoom out feature in diagram builder

### ISSUE THREAD

**Issue by mndpsngh21** [liferay/alloy-ui#108]
Hi All,

  I am using diagram builder for my project I am facing issue that if i scale diagram-builder for zoom out diagram as diagram is very large in size, connectors are not coming according to scale level.please guide me how to implement zoom in and zoom out feature

**Comment by bryceosterhaus** [comment]
AlloyUI is deprecated and only critical patches will be applied. 

If you believe this is a critical issue, please re-open at [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/issues/new/choose).
