### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by adeonir** [liferay/alloy-ui#112]
Olá, estou trabalhando em um projeto que usa esse repositório, mas estou tendo erro nessa dependência:
https://github.com/liferay/alloy-ui/blob/master/bower.json#L18

```
bower yui3#patched-v3.18.1                not-cached git://github.com/liferay/yui3.git#patched-v3.18.1
bower yui3#patched-v3.18.1                   resolve git://github.com/liferay/yui3.git#patched-v3.18.1
bower yui3#patched-v3.18.1                   ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/life
ray/yui3.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.253.112]: errno=Resource tem
porarily unavailable github.com[1: 192.30.253.113]: errno=Resource temporarily unavailable

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Resource temporarily unavailable
```

**Comment by Robert-Frampton** [comment]
Hey @adeonir, thanks for reporting the issue.

I was able to successfully run `bower install` on master just now. It could have been that github was just down when you tried installing.

If it still doesn't work for you, can you provide us with your version of Node, npm, and bower, as well as your OS?

**Comment by adeonir** [comment]
Hi @Robert-Frampton. Thanks for the quick answer.

Yesterday I've tried to install on Windows 10 and macOS Sierra with the latest versions of node, npm and bower.

It worked now without problems.
