### ISSUE TITLE
 diagram builder returning xy wrong position from toJSON method

### ISSUE THREAD

**Issue by tbacalhau** [liferay/alloy-ui#116]
Good afternoon!

I'm having difficulty retrieving the object's position using the toJSON method of DiagramBuilder.
I can retrieve position X and Y, but they are returning with a high value, because when I add the object using addField it gets in a position far away from what was correct.

**Comment by bryceosterhaus** [comment]
AlloyUI is deprecated and only critical patches will be applied. 

If you believe this is a critical issue, please re-open at [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/issues/new/choose).
