### ISSUE TITLE
Is there a version for Bootstrap 4?

### ISSUE THREAD

**Issue by oshingc** [liferay/alloy-ui#123]
Hi guys.
I wonder if you're thinking in work in a version compatible with Bootstrap 4.

**Comment by jonmak08** [comment]
Hi @oshingc,

Unfortunately, Alloy UI is being deprecated and nothing new is being added to the project; so a new Bootstrap 4 compatible version will not be developed.  We are strictly in maintenance mode on this project going forward.

Sorry for the inconvenience!

Please let me know if you have any questions. Thanks!
