### ISSUE TITLE
Diagram Builder how do I use property of "fieldsDragConfig"

### ISSUE THREAD

**Issue by yang5664** [liferay/alloy-ui#124]
I have been looking example for "fieldsDragConfig", but I didn't find, please help me.

![screen shot 2018-02-28 at 1 40 45 am](https://user-images.githubusercontent.com/5953010/36744776-9acf4f54-1c28-11e8-859a-b19e8326634f.png)

**Comment by bryceosterhaus** [comment]
AlloyUI is deprecated and only critical patches will be applied. 

If you believe this is a critical issue, please re-open at [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/issues/new/choose).
