### ISSUE TITLE
Update row height of Scheduler

### ISSUE THREAD

**Issue by aboigne** [liferay/alloy-ui#125]
I want to change the height of a row in scheduler. 
For example, in a dayView, I set the 'hourHeight' property, but it doesn't work. The hourHeight stay at 52px, the default value.
When I change others properties, it work, but not this one.

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects). If this is still an issue, please re-open on that repository.
