### ISSUE TITLE
Safari Mac 

### ISSUE THREAD

**Issue by waqar2012** [liferay/alloy-ui#128]
Schedule is not rendering on the Safari Mac Can you help on this regard.

**Comment by jonmak08** [comment]
Hi @waqar2012,

I just tested the ```aui-scheduler``` in Safari (_Version 11.1.1 (13605.2.8)_) on my Mac (_High Sierra 10.13.5_) and it rendered fine.  Please see below:

![image](https://user-images.githubusercontent.com/860951/41262206-5bb707b8-6d94-11e8-8104-fb7b509e78f4.png)

Can you provide your browser and OS information?

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Closing issue as there has been no update.  If you feel there is still a problem, please feel free to reopen the issue and add additional comments.

Thank you!
