### ISSUE TITLE
Show More in Scheduler ui

### ISSUE THREAD

**Issue by waqar2012** [liferay/alloy-ui#129]
I need to show the schedule element of that day when user click on the show more rather then as popup overlay.
suppose when i click the month view then show more appear in the 10th of the month then i click that show more it shows the 10th of month in that day.
Can you assist me on this?
regards,
waqar

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
