### ISSUE TITLE
How to open the loader in popup over button "Edit" on Schedule

### ISSUE THREAD

**Issue by waqar2012** [liferay/alloy-ui#130]
My Ajax loader is not fired when i click edit button in schedule Popup over button.  But when i debug its show the loader but normal running not showing the loader,
Can you help me on this?
i am also sharing the code where i am changing the code in the click event. file name aui-schedule-event-min.js
_handleSaveEvent: function(event) {
			var instance = this;
			
			try{instance.fire(EV_SCHEDULER_EVENT_RECORDER_Loader);
			}catch(err){console.log(err);}
			showLoader();// ajax loading 
			instance.fire(
				instance.get(EVENT) ? EV_SCHEDULER_EVENT_RECORDER_EDIT : EV_SCHEDULER_EVENT_RECORDER_SAVE,
				{
					newSchedulerEvent: instance.getEventCopy()
				}
			);

			event.preventDefault();
		}

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
