### ISSUE TITLE
In Time box my schedule event is not aligned its go to other time Box

### ISSUE THREAD

**Issue by waqar2012** [liferay/alloy-ui#131]
Hi Support team my my schedule event is going to other box like 1:42 PM  but it also touching the other time box 2:00 PM. how can i fix rather than go to the next time box. as shown in the attached image.

![box is not aligned in 1pm](https://user-images.githubusercontent.com/20204830/41521925-1ea95ec4-72e5-11e8-8ea6-efa351166f1f.png)

Remaining how can i show the minimum number of task in particular time box rather than overlapping to each other.  
please help me regarding this.

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
