### ISSUE TITLE
How to set custom time view on SchedulerWeekView  

### ISSUE THREAD

**Issue by tarun-techmarbles** [liferay/alloy-ui#132]
**i need to set custom time on a scheduler from 6 am to 9 pm only not 24hr** 
        YUI().use(
            'aui-scheduler',
            function(Y) {
                var weekView = new Y.SchedulerWeekView();
                var monthView = new Y.SchedulerMonthView();
                var eventRecorder = new Y.SchedulerEventRecorder();

                schedule = new Y.Scheduler({
                    activeView: weekView,
                    boundingBox: '#myScheduler',
                    date: new Date(2018, 6, 29),
                    eventRecorder: eventRecorder,
                    items: '',
                    render: true,
                    views: [weekView, monthView]
                });
                $(".btn-finish").click(function() {
                    console.log(schedule.getEvents());
                });

            });

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
