### ISSUE TITLE
Diagram builder connector overrides delete and backspace actions for other fields

### ISSUE THREAD

**Issue by bsasschetti** [liferay/alloy-ui#133]
Example: 

1. Go to Alloyui [real word example](https://alloyui.com/examples/diagram-builder/real-world)
2. Select any connector
3. Try to erase name attribute on settings panel, using **`delete`** or **`backspace`** keys.
4. Alert asking for connector deletion confirmation appears.

If you try doing the same with a node instead of a connector, it works properly.
Also it overrides the behaviour for other inputs outside the embedded diagram.
I made a little bit of debugging and researching because I thought it was some bug introduced by me, but then I realised that, when you click on input element before going for step 3 from above, the connector element seems not to lose the 'active' status, so the right part of 
[this conditional](https://github.com/liferay/alloy-ui/blob/5b4ad2a8d5cb3ab362979e4fb470fcf1eea5ba39/src/aui-diagram-builder/js/aui-diagram-builder.js#L795) is returning **`false`**

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
