### ISSUE TITLE
Show weeknumber in datepicker?

### ISSUE THREAD

**Issue by nrbn** [liferay/alloy-ui#141]
**Datepicker missing weeknumber. I want to show weeknumber for each week, is it possible? Here is the code:**

`YUI({ lang: 'nb-no' }).use(
  'aui-datepicker',
  function(Y) {
    new Y.DatePicker(
      {
        trigger: '.datepicker-btn',
        popover: {
          zIndex: 99999
        },
        weekDays: true,
        firstDayOfWeek: 1
      }
    );
  }
);`

![image](https://user-images.githubusercontent.com/10879727/47707785-f4e32a00-dc2c-11e8-81a3-656d2e52392a.png)

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
