### ISSUE TITLE
Tooltip is shown right after init

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [liferay/alloy-ui#142]
Tooltips should be IMHO hidden by default and shown when the specified event is fired. This behavior can be tested directly in the Example section:
https://alloyui.com/examples/tooltip

In my case I also tried `render: false` option, but this has no effect.

**Comment by jonmak08** [comment]
Hi @jan-tosovsky-cz,

You can achieve you desired result of not having the tooltip displayed on load by adding the attribute `visible: false` to your configuration object on component instantiation.

Ex.
```javascript
YUI().use(
  'aui-tooltip',
  function(Y) {
    new Y.Tooltip(
      {
        trigger: '#myTooltip',
        position: 'right',
        visible: false
      }
    ).render();
  }
);
```

Please let me know if you have any questions. Thanks!
