### ISSUE TITLE
Found a bug in SchedulerWeekView

### ISSUE THREAD

**Issue by nrbn** [liferay/alloy-ui#143]
Found a bug in SchedulerWeekView. I have firstDayOfWeek: 1 and added event sunday 31.march.2019. And it appear on saturday 30.

https://jsfiddle.net/nrbnvel/t13b2xy5/38/

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
