### ISSUE TITLE
Multiple day selection in week view

### ISSUE THREAD

**Issue by chiragpurohit71085** [liferay/alloy-ui#144]
Is there any way I can select multiple days i.e 2 pm Wed to 1 pm Thursday?

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
