### ISSUE TITLE
DatePicker doesn't show a message informing that the date pasted in the field is invalid. Instead it sets the current date

### ISSUE THREAD

**Issue by rodrigopaulino** [liferay/alloy-ui#146]
**Steps to Reproduce**

1. Paste an invalid date, e.g. 02/04/20182222222, in a date field that uses A.DatePicker;
2. Click outside the field.

**Actual Behavior**
DatePicker is rendered and _current date_ is set on date field.

**Expected Behavior**
The text "_Invalid Date_" should be set on the field and the DatePicker should still be able to render.

**Comment by rodrigopaulino** [comment]
Hey, guys.
Do you have any estimative on this will be reviewed?
This information would help me a lot since I have the customer waiting for the fix.

Here's the https://github.com/jonmak08/alloy-ui/pull/440

**Comment by jonmak08** [comment]
Hey @rodrigopaulino,

I'll be reviewing this today.  Sorry for the delay.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Reviewed and Merged.  See https://github.com/liferay/alloy-ui/compare/efdff6c050d5cfcc069028ca48b410f0baca3a18...d9f384cc2851f81a18f13d7678a725dccf46a40f
