### ISSUE TITLE
Migrate alloyui.com to GitHub pages

### ISSUE THREAD

**Issue by SerenaGOT** [liferay/alloy-ui#150]
Hi, I am trying this tool but your documentation website is down. I can't check the doc for the alloy-ui scheduler. Can anyone fix it? Thank you so much

**Comment by wincent** [comment]
The hosting platform we were using shut down so we will need to migrate to GitHub pages. In the meantime you may be able to get the info you're looking for from the website repo: https://github.com/liferay/alloyui.com

For example:

- https://github.com/liferay/alloyui.com/blob/1bfc60eb9f482b579bfa8b3750815a3e4a873b60/src/documents/tutorials/scheduler/index.html.md.eco
- https://github.com/liferay/alloyui.com/search?q=scheduler&unscoped_q=scheduler

**Comment by SerenaGOT** [comment]
Hi, Thanks for the link, but I am still stuck with understanding how to use event and eventRecorder in the scheduler. For example, if I want to change the color of an event when saving it. I use 

`  var eventRecorder = new Y.SchedulerEventRecorder({
      on: {
        save: function(event) {
            this.set("color","#000000");
        }
      }
    });`

But it would only change the next event I create not the current one that I want to set. 
Could you show me an example of the SchedulerEventRecorder since I cannot find the example on the current website. Thank you so much!

**Comment by findela** [comment]
What about the current status of the documentation building platform?

**Comment by wincent** [comment]
@SerenaGOT: I'm afraid I don't have any examples beyond what is in the documentation (I've not actually used Alloy UI myself yet, I'm just helping with the website); can I ask you to create a separate issue with your question in it, for better visibility?

@findela: I'm not sure I understand your question; could you please clarify? Thanks.

**Comment by findela** [comment]
@wincent alloyui site is not reachable,I was looking for more design related docs - how to change calendar styling and ux through the functions which I have found earlier in docs,can you help me those customise styling instructions/api?

Thanks

**Comment by scheriam** [comment]
In the meantime you could try to use the Internet Archive to browse a bit through the documentation:
https://web.archive.org/web/20190128223856/https://alloyui.com/
(to reach the navigation on the top of the page, you need to close the WayBackMachine toolbar with the x in the top right corner)

**Comment by jonmak08** [comment]
https://alloyui.com/ has been restored.  We apologize for any inconvenience this may have caused.

Please let me know if you have any questions. Thanks!

**Comment by findela** [comment]
@jonmak08 Still loading the site,not working.Just checked.

**Comment by jonmak08** [comment]
Hey @findela,

The site loads perfectly fine for me and a few others on various devices.  You can try to also hit http://liferay.github.io/alloyui.com which should redirect to https://alloyui.com/.

See screenshot for website loading correctly.
![alloyui](https://user-images.githubusercontent.com/860951/57280949-cb351080-705e-11e9-9f03-624fdf1c64e8.png)

Please let me know if you have any questions.  Thanks!

**Comment by wincent** [comment]
Looks like `alloyui.com` is resolving to 185.199.18.153 and 185.199.109.153. 

I think that first one is a typo and should be 185.199.108.153. Reason it works for @jonmak08 and not @SerenaGOT is their DNS servers don't necessarily need to return the same IP.

```
~ ❯ dig alloyui.com                                                                                                                                                                                                                           ~

; <<>> DiG 9.10.6 <<>> alloyui.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18354
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1024
;; QUESTION SECTION:
;alloyui.com.                   IN      A

;; ANSWER SECTION:
alloyui.com.            300     IN      A       185.199.18.153
alloyui.com.            300     IN      A       185.199.109.153

;; AUTHORITY SECTION:
alloyui.com.            171813  IN      NS      jim.ns.cloudflare.com.
alloyui.com.            171813  IN      NS      sofia.ns.cloudflare.com.

;; ADDITIONAL SECTION:
sofia.ns.cloudflare.com. 76582  IN      A       173.245.58.223
sofia.ns.cloudflare.com. 76072  IN      AAAA    2400:cb00:2049:1::adf5:3adf

;; Query time: 32 msec
;; SERVER: 192.168.40.1#53(192.168.40.1)
;; WHEN: Tue May 07 09:20:25 CEST 2019
;; MSG SIZE  rcvd: 168

~ ❯ dig liferay.github.io +noall +answer                                                                                                                                                                                                0.22s ~

; <<>> DiG 9.10.6 <<>> liferay.github.io +noall +answer
;; global options: +cmd
liferay.github.io.      3599    IN      A       185.199.111.153
liferay.github.io.      3599    IN      A       185.199.108.153
liferay.github.io.      3599    IN      A       185.199.110.153
liferay.github.io.      3599    IN      A       185.199.109.153
```

**Comment by findela** [comment]
I am looking for API Docs as I am intended to integrate with vue project,looking for theming changes,which is not getting.

**Comment by jonmak08** [comment]
Hey @findela,

The API docs have been restored.  You can now access them at https://alloyui.com/api/.

Please let me know if you have any questions. Thanks!
