### ISSUE TITLE
Displaying error container prevent fireing other events

### ISSUE THREAD

**Issue by rolandpakai** [liferay/alloy-ui#154]
**Steps to Reproduce**
Create a form with a required input field which is focused when the form is opened and a checkbox with a toggle click function.
After the form is opened the cursor is in the input field.
Now click on the checkbox.

**Actual Behavior**
The input field is validated and the aui-toggler-base.js::toggle function is not fired

**Expected Behavior**
The input field is validated and the aui-toggler-base.js::toggle function fired

https://issues.liferay.com/browse/LPS-99755

**Comment by orsolyalukacs** [comment]
I created a possible fix and sent a PR.
https://github.com/liferay/alloy-ui/pull/155
