### ISSUE TITLE
Validation for fields Does not work properly.

### ISSUE THREAD

**Issue by pratikpatel1174** [liferay/alloy-ui#161]
I have two radio buttons and two textboxes with custom validator of Regular Expression. If I select the first radio button then validate textbox1 and ignore the required validation of textbox2 and vice versa for another radio button selection

**Comment by bryceosterhaus** [comment]
AlloyUI is now deprecated and it's location is being moved to [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party/projects/alloy-ui). If this is still an issue, please re-open on that repository.
