### ISSUE TITLE
Link element is including obsolete charset attribute

### ISSUE THREAD

**Issue by antonio-ortega** [liferay/alloy-ui#164]
**Steps to Reproduce**
Load css files that would be added to the DOM in a link element.
Run [W3C official validation](https://validator.w3.org/)

**Actual Behavior**
There is no errors. 

**Expected Behavior**
You can see the error:

> Error: The charset attribute on the link element is obsolete. Use an HTTP Content-Type header on the linked resource instead.

You can see same information about using charset attribute in link elements in [W3C documentation](https://www.w3.org/TR/html50/obsolete.html).

**Comment by jonmak08** [comment]
This has been resolved.  Please see https://github.com/jonmak08/yui3/pull/45.
