### ISSUE TITLE
AUI Plugin Guide

### ISSUE THREAD

**Issue by jonathantneal** [liferay/alloy-ui#27]
Would you help me write an AUI plugin? I work for this cool company that builds cool things, and - anyway - I want to build cool things with Alloy.

My only problem is - I'm having trouble learning how to write an Alloy plugin.

I have all sorts of ideas for things I would like to write.

Now, to be fair, there's a YUI guide for this, http://yuilibrary.com/yui/docs/plugin/, but they break up the code in their examples, and they don't provide a final, all-together example that I can download and tinker with. I learn by tinkering.

http://alloyui.com/ does a great job of making things accessible to new developers. Could we do something like this for aspiring Alloy plugin developers?

Thanks for hearing me out.

**Comment by manpreetssethi** [comment]
@zenorocha I found out about AlloyUI recently, and it's awesome! That said, would love to extend the library to write some plugins, but can't find the documentation, some examples perhaps?

Thanks in advance.

**Comment by netlander** [comment]
Liferay are moving away from alloyUI more towards JQuery/Bootstrap 3.

**Comment by eduardolundgren** [comment]
Actually, our core components will use @metal as core. Metal.js creates a jQuery plugin for each component written on it, and for HTML markup we will go with Bootstrap 3 syntax.

**Comment by netlander** [comment]
Will this be for 7.0 or later?

**Comment by jonathantneal** [comment]
That all sounds pretty neat. http://metaljs.com/

You folks sure do make cool things.

Does this mean my issue resolved by https://github.com/metal/metal.js/wiki/Creating-your-own-component ? If so, I’ll consider this issue resolved and report this sweet news back to my senior engineer.
