### ISSUE TITLE
Ace Editor - search box error

### ISSUE THREAD

**Issue by ghost** [liferay/alloy-ui#78]
When i try to use Ctrl-F to search in the ace editor frame, i receive the following error (happens also at the AlloyUI Example Page).

NetworkError: 404 Not Found - http://alloyui.com/examples/ace-editor/ext-searchbox.js

**Comment by IgorMarques** [comment]
I'm getting this error too. It's a rails app deployed at heroku. You can check it the "implementation" field in this form here:

http://that-s-the-way-you-do-it.herokuapp.com/docs/new

Running local everything is fine.

**Comment by bryceosterhaus** [comment]
AlloyUI is deprecated and only critical patches will be applied. 

If you believe this is a critical issue, please re-open at [liferay-frontend-projects](https://github.com/liferay/liferay-frontend-projects/issues/new/choose).
