### ISSUE TITLE
Website Bugs

### ISSUE THREAD

**Issue by lifeart** [liferay/alloy-ui#79]
In page http://alloyui.com/tutorials/image-viewer/
Tabs: Basic Example, Gallery Example, Real World Example

Images clickable, but default event not catched, image onclick => just opens as basic image file in current tab (Chrome);

**Comment by zenorocha** [comment]
This PR https://github.com/liferay/alloyui.com/pull/186 fixes this issue. It will be live pretty soon.

**Comment by zenorocha** [comment]
Thanks for reporting @lifeart :D

**Comment by zenorocha** [comment]
Done, clear your cache and you'll see it fixed

**Comment by lifeart** [comment]
Awesome!

**Comment by lifeart** [comment]
zenorocha, have jou any idea about using DatePicker as Month/Year selector, without Days? 
Now only one way: 
```
.yui3-calendar-grid {
         display:none;
}
.yui3-calendar-header {
        width: 200px;
        height: 20px;}
}
```
But, this is not usable and hard to select month+-6 and year+-1 (many clicks);
