### ISSUE TITLE
CDN 

### ISSUE THREAD

**Issue by megastef** [liferay/alloy-ui#84]
I get this error message when loading alloyui from CDN from the given tutorials:

```
Font from origin 'http://cdn.alloyui.com' has been blocked from loading by Cross-Origin Resource Sharing policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1337' is therefore not allowed access.
```

**Comment by zenorocha** [comment]
Thanks for reporting @megastef, we requested our provider to add this header and we'll let you know when it's done.

**Comment by natecavanaugh** [comment]
Hi @megastef 
This should be working now (I tested it and it is now sending the proper headers).
I'm going to close this one out, but let me know if you are still having an issue.

Thanks again for the heads up :)
