### ISSUE TITLE
yui is no longer under maintained,so why not make this project base on jquery.jquery is also fancy

### ISSUE THREAD

**Issue by hiwjcn** [liferay/alloy-ui#85]
thank you all

**Comment by jonmak08** [comment]
Hi @hiwjcn,

@natecavanaugh has posted a blog about the future of Alloy UI as discuss and decide what will be best.  You can read the blog at https://www.liferay.com/web/nathan.cavanaugh/blog/-/blogs/yui-liferay-and-the-future.

Please let me know if you have any questions.  Thanks!
