### ISSUE TITLE
support for saving/loading form built by form-builder ?

### ISSUE THREAD

**Issue by michaelnguyen2021** [liferay/alloy-ui#92]
I need to save/load the forms built by form-builder (http://alloyui.com/examples/form-builder/).

Is there a toJson method or anyway to extra meta-data so I can save form meta-data to a database ?

**Comment by brunobasto** [comment]
There is no toJSON method by default, but one way of doing that would be:

var serializedFields = [];

formBuilder.get('fields').each(
	function(field) {
		serializedFields.push(
			{
				name: field.get('name'),
				showLabel: field.get('showLabel')
				...
			}
		);
	}
);

**Comment by stiemannkj1** [comment]
@duynguyen0511,
Check out [my Q&A on StackOverflow](http://stackoverflow.com/questions/40724375/how-can-i-save-and-restore-alloyui-formbuilder-fields/40724376), and see if it answers your question.

\- Kyle
